# Generated by Django 2.2.6 on 2020-01-19 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prashnottari', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmarking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
